name: Verify CI
run-name: "Verify ${{ github.event.pull_request && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('`{0}` on {1}', github.event.head_commit.message, github.ref) }}"

on:
  pull_request:
    branches: [main]
  push:
  workflow_call:

jobs:
  verify:
    needs: [build, fmt, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo -e "Do green eggs come from \e[3mGallus varius\e[0m?"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - run: pnpm build:release

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - run: pnpm fmtcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: sudo apt-get install xvfb -y
      - run: pnpm i
      - run: pnpm build:test
      - run: xvfb-run -a pnpm test
